version: "3.1"

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
